/***************CREACION BASE DE DATOS**********************/
CREATE DATABASE MEXTIZADB;
USE MEXTIZADB;

/***************  CREACION DE TABLAS  **********************/
CREATE TABLE USUARIO(
ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
CORREO VARCHAR(50) NOT NULL,
PASS VARCHAR(20)NOT NULL,
TELEFONO VARCHAR(20)NULL,
DIRECCION VARCHAR(100)NOT NULL,
ROL VARCHAR(30) NOT NULL,
ESTATUS BIT NOT NULL
);

CREATE TABLE SUCURSAL(
ID_SUCURSAL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DIRECCION VARCHAR(100)NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
ID_USUARIO INT NOT NULL,
ESTATUS_SUCURSAL BIT NOT NULL,
IMAGEN LONGBLOB NULL);

CREATE TABLE PRODUCTO(
ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
TIPO VARCHAR(30) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(100) NOT NULL,
PRECIO FLOAT NOT NULL,
ESTATUS BIT NOT NULL
);

CREATE TABLE PEDIDOS(
ID_PEDIDOS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_SUCURSAL INT NOT NULL,
ID_USUARIO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT NOT NULL,
OBSERVACION VARCHAR(100),
ESTATUS BIT NOT NULL
);


CREATE TABLE COMENTARIOS(
ID_COMENTARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_SUCURSAL INT NOT NULL,
ID_USUARIO INT NOT NULL,
COMENTARIO VARCHAR(100) NULL,
FECHA DATE NOT NULL 
);

CREATE TABLE COMENTARIOSG(
ID_COMENTARIOSG INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
CORREO VARCHAR(30) NOT NULL,
COMENTARIO VARCHAR(100) NOT NULL,
FECHA DATE NOT NULL
);



/***************CREACION DE LLAVES FORANEAS**********************/
ALTER TABLE SUCURSAL ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);
ALTER TABLE PEDIDOS ADD FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
ALTER TABLE COMENTARIOS ADD FOREIGN KEY(ID_SUCURSAL) REFERENCES SUCURSAL(ID_SUCURSAL);
ALTER TABLE COMENTARIOS ADD FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO);

/*  DROP DATABASE MEXTIZADB */
/***************    INSERCION DE DATOS    **********************/
/*TIPO DE ROLES: 1.-ADMINISTRADOR
				 2.-GERENTE
                 3.-USUARIO*/
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('JUAN SILVESTRE','RAMÍREZ BECERRA','trebol_silvestre_en4@hotmail.com','tacosZas123',4774408656,'BRICHO# 213,37108,VALLE HERMOSO, LEON, GUANAJUATO','DISTRIBUIDOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('JOSÉ MARTÍN','RUIZ COSS','MARTIN69ENCUATRO@gmail.com','ZaZatacos666',4733564189,'Anegeles# 235,35103,LEON MODERNO, LEON, GUANAJUATO','ADMINISTRADOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('ANGEL CHRISTIAN','ALVAREZ TRUJILLO','trujillo69@hotmail.com','VamosTacos123',4772634859,'DONATELO# 313,39101,LEON 1, LEON, GUANAJUATO','ADMINISTRADOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('ARGEL','ARENAS ORTIZ','ARENAS32@gmail.com','ZaZatacos666',4733564189,'Anegeles# 235,35103,ECHEVESTE, LEON, GUANAJUATO','DISTRIBUIDOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('EL ROBER','EL ENGAÑAO','VEN4Y69@gmail.com','123',4733564189,'SOLAMA# 235,35103,LA MISERIA, LEON, GUANAJUATO','DISTRIBUIDOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('ÁNGELICA','GAUCIN','angelica_gg@gmail.com','1234',4733564189,'ROMA# 234,35103,Lusdunum Convenarum , ROMA','DISTRIBUIDOR',1);
INSERT INTO USUARIO(NOMBRE,APELLIDO,CORREO,PASS,TELEFONO,DIRECCION,ROL,ESTATUS) VALUES('ALBERTO','GONZALES ROCHA','ALBERTOROCH@gmail.com','DELTAZELTAOMEGA',4774851623,'COBRE# 124,35103,ECHEVESTE , LEON, GUANAJUATO','ADMINISTRADOR',1);

INSERT INTO SUCURSAL(TELEFONO,NOMBRE,DIRECCION,DESCRIPCION,ID_USUARIO,ESTATUS_SUCURSAL) VALUES(4778956235,'OXXO Echeveste','Torneros de echeveste,37125,Echeveste, LEON, GUANAJUATO','Horario de lunes a viernes de 12:00hrs - 20:00hrs, estamos a tus órdenes',2,1);
INSERT INTO SUCURSAL(TELEFONO,NOMBRE,DIRECCION,DESCRIPCION,ID_USUARIO,ESTATUS_SUCURSAL) VALUES(4775961248,'Extra Cedro','Cedro,37125,Vilas de San juan, LEON, GUANAJUATO','Horario de jueves a domingo de 20:00hrs - 3:00hrs, estamos a tus órdenes',4,1);
INSERT INTO SUCURSAL(TELEFONO,NOMBRE,DIRECCION,DESCRIPCION,ID_USUARIO,ESTATUS_SUCURSAL) VALUES(4778254896,'Miscelanea Caro','Cartoneros,37125,Rivera de la presa, LEON, GUANAJUATO','Horario de lunes a viernes de 10:00hrs - 18:00hrs, estamos a tus órdenes',5,1);
INSERT INTO SUCURSAL(TELEFONO,NOMBRE,DIRECCION,DESCRIPCION,ID_USUARIO,ESTATUS_SUCURSAL) VALUES(4771234957,'Delicias Ricarda','Ortigilla,37125,Delta, LEON, GUANAJUATO','Horario de lunes a sabado de 18:00hrs - 4:00hrs, estamos a tus órdenes',6,1);

/*TIPO DE ALIMENTOS: BEBIDAS Y ALIMENTOS*/
INSERT INTO PRODUCTO(TIPO,NOMBRE,DESCRIPCION,PRECIO,ESTATUS) VALUES('SALSA','SALSA MACHA','Envase de vidrio de 230gr. - Chile tostado (Picoso)',39,1);
INSERT INTO PRODUCTO(TIPO,NOMBRE,DESCRIPCION,PRECIO,ESTATUS) VALUES('SALSA','SALSA SAN MARQUEÑA','Envase de vidrio de 250gr. - Chile de árbol y chile morita',59,1);


